### ISSUE TITLE
Missing Linux python 3.8 GitHub release asset

### ISSUE THREAD

**Issue by benknight135** [i3drobotics/pyphase#21]
Missing dash in release asset upload due to invalid line in `.github/workflows/release.yml`
```
- name: Upload Linux wheel release assets
  uses: softprops/action-gh-release@v1
  with:
    tag_name: v${{ env.PROJ_VER }}
    files: |
      deployment/phase-${{ env.PROJ_VER }}cp38-cp38-linux_x86_64.whl
```
line 388
```
deployment/phase-${{ env.PROJ_VER }}cp38-cp38-linux_x86_64.whl
```
Should be 
```
deployment/phase-${{ env.PROJ_VER }}-cp38-cp38-linux_x86_64.whl
```
